name: Lint & Test

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  lint-and-test:
    runs-on: windows 
    strategy:
      matrix:
        project: [backend, website, admin-dashboard, mobile]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node (for web/admin)
        if: matrix.project != 'mobile'
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Setup Flutter
        if: matrix.project == 'mobile'
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
      - name: Run linters and tests
        run: |
          if [ "${{ matrix.project }}" = "mobile" ]; then
            cd mobile && flutter pub get && flutter analyze && flutter test
          else
            cd ${{ matrix.project }} && npm ci && npm run lint && npm test || true
          fi
